name: CI docker image
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mlabs/hello-app:${{ github.sha }}

      - name: Success message
        run: echo "Successfully built hello-app docker image from $GITHUB_SHA"
